### ISSUE TITLE
Initialize VTS to the location of the GeoJson loaded 

### ISSUE THREAD

**Issue by mghildiy** [Melown/vts-browser-js#106]
Hi,

I am working on a VTS based web app.

I plan to read GeoJson data from a URL. I want that my app is initialized to this data, like appropriate positioning of camera etc.

How can this be achieved?

**Comment by DavidLevinsky** [comment]
Hello,

you can take an inspiration from this example which loads GeoJson form URL:
https://jsfiddle.net/2sowet7x/

some parts of code for positioning of camera can be found there:
https://jsfiddle.net/3sr0d8g5/show/

More examples:
https://github.com/Melown/vts-browser-js/wiki/Examples

**Comment by mghildiy** [comment]
Thanks for the update.

I have another query. Can I extend VTS to enable user to interact with my map? Like, I want to render a point cloud, and enable user to draw bounding volumes around objects in the point cloud, like trees,houses, road signs etc. Can this be achieved with VTS?

**Comment by DavidLevinsky** [comment]
VTS Browser does not support point clouds. But VTS Browser is open source, so you can add support for point clouds to the rendering pipeline.

**Comment by mghildiy** [comment]
Thanks for inputs.
