### ISSUE TITLE
Can we draw a structure (During the runtime) using VTS ?

### ISSUE THREAD

**Issue by lohithkarlapudi** [Melown/vts-browser-js#111]
Hi,

I just wanted to know if we can draw any objects or structures like a cube or something after the scene has been rendered on the browser. Is there any functionality available on VTS which will enable me to do so? Please Provide me with some insights regarding that. 

Thank You,

**Comment by DavidLevinsky** [comment]
Hi,

yes, you can render additional objects. There are examples which can be interesting for you:
https://jsfiddle.net/Lzb2o5uj/
https://jsfiddle.net/2uubdxa7/

More examples can be found there:
https://github.com/Melown/vts-browser-js/wiki/Examples
or there:
https://github.com/Melown/vts-browser-js/tree/master/demos
