### ISSUE TITLE
MultiPoint not rendered

### ISSUE THREAD

**Issue by mghildiy** [Melown/vts-browser-js#114]
In my GeoJson fetched from server only Point features are present, and they render well.

I have defined style as:

> var style = {
        'constants': {
            '@icon-marker': ['icons', 6, 8, 18, 18]
        },
    'bitmaps': {
            'icons': 'http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png'
        },

So I can see green circles rendered.

But if I replace points and instead put MultiPoint features in GeoJson, with rest unchanged,
I don't see features rendered.

What can be the cause?

**Comment by DavidLevinsky** [comment]
It should be fixed in new version (2.16.0)
