### ISSUE TITLE
Calculating pixels to coordinates

### ISSUE THREAD

**Issue by mogmog** [Melown/vts-browser-js#115]
Does the api support a way to determine how many degrees 100 pixels is represented by at the current zoom level?

**Comment by DavidLevinsky** [comment]
Hello, what a strange request :) Yes it is possible to calculate that. 

angle = (((100 / browser.renderer.getCanvasSize()[1]) * browser.map.getPosition().getViewExtent()) / (earthDiameter*Math.PI)) * 360;

average earth diameter is approximately 12 7348 000 m 
You will probably also need to clamp result to max. 180 deg

angle = Math.min(180, angle);
