### ISSUE TITLE
cdn.melown.com certificate expired

### ISSUE THREAD

**Issue by hthetiot** [Melown/vts-browser-js#117]
https://cdn.melown.com/libs/vtsjs/browser/v2/vts-browser.min.js

Reproduce:
- Open Doc: http://vtsdocs.melown.com/en/latest/tutorials/geojson.html
- Open "live demo": https://jsfiddle.net/1xf3bxz9/ 

Result:
> Failed to load resource: net::ERR_CERT_DATE_INVALID vts-browser.min.js
- https://www.ssllabs.com/ssltest/analyze.html?d=cdn.melown.com&latest

Expected:
> Serve static.

Solution:
- Free SSL via certbot in crontab -> https://letsencrypt.org/getting-started/

**Comment by DavidLevinsky** [comment]
Thank you for the report. It should be fixed by now.
