### ISSUE TITLE
How do I make state names in uppercase?

### ISSUE THREAD

**Issue by johntrigub** [Melown/vts-browser-js#118]

**Comment by DavidLevinsky** [comment]
You have to modify file with free layer styles or overwrite free layer styles programmatically. More about free layer styles can be found at this link:
https://github.com/Melown/vts-browser-js/wiki/VTS-Geodata-Format#geo-layer-styles-structure
You can convert names to uppercase by following way:
"label-source" : { "uppercase" : "$name" } 
I have made example which present how to change map style programmatically :
https://jsfiddle.net/g3h1xkt6/1/
More about related concepts can be found at this link:
http://vtsdocs.melown.com/en/latest/tutorials/index.html#frontend

**Comment by johntrigub** [comment]
Thank you very much!!
