### ISSUE TITLE
Uncaught TypeError: this.ui.setControlDisplayState is not a function

### ISSUE THREAD

**Issue by johntrigub** [Melown/vts-browser-js#123]
On some Chrome browsers there is such an error and the map does not start:

vts-browser.min.js:5 Uncaught TypeError: this.ui.setControlDisplayState is not a function
at new b (vts-browser.min.js:5)
at new l (vts-browser.min.js:5)
at Object.r (vts-browser.min.js:5)
at startDemo (sample-app-rest.js:14)
at sample-app-rest.js:27

**Comment by DavidLevinsky** [comment]
Thanks for the report. Good news is that this error will be fixed in next version of the library. Bad news is that this error can occur only when WebGL in not supported.
