### ISSUE TITLE
loading page

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-browser-js#133]
Sorry, new to this, so not sure if this is the right place.

I'm getting issues when trying to load map from Melown cloud using the vts-browser with js.

Access to XMLHttpRequest at 'https://cdn.melown.com/vts/melown2015/terrain/global/viewfinder3/0-0-0.meta?3' from origin 'https://www.holoceneadventures.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

vts-browser.min.js:5 GET https://cdn.melown.com/vts/melown2015/terrain/global/viewfinder3/0-0-0.meta?3 403

**Comment by ladislavhorky** [comment]
Hello Jonathan,

we have been moving our servers so there might have been glitch, I have no trouble with the given request when accessing the page now. Is the error still present? If so, could you please:

1) Try the request again (e.g. clicking the link above)
2) If it fails, send us the request with the time (+ timezone) and country of origin so we can look the issue up in our logs on the right server? 

Thanks and sorry for inconvenience,
Ladislav

**Comment by jrjdavidson** [comment]
Hi Ladislav,

I've noticed now that I have the same issue across all melown cloud maps and datasets, even when trying to view resources and maps in melown cloud console.

username on melown cloud is jonathan.davidson@canterbury.ac.nz - this might be more useful than the request time? 

Otherwise, this screenshot and network details might help:

![temp](https://user-images.githubusercontent.com/46798391/51436350-2e897580-1cf0-11e9-80f8-e823bf698feb.png)

HTTP/1.1 404 Not Found
Server: nginx/1.6.2
Date: Sun, 20 Jan 2019 07:09:09 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Content-Encoding: gzip

Cheers

**Comment by jrjdavidson** [comment]
Futhermore- this issue only comes up in chrome

**Comment by tomasKavan** [comment]
Hi Jonathan,

I just checked and all map resources from our CDN server at Sydney are served with proper CORS header:

```
root@sydney:~# curl --head https://cdn.melown.com/vts/melown2015/terrain/global/viewfinder3/0-0-0.meta

HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Sun, 27 Jan 2019 21:56:05 GMT
Content-Type: application/octet-stream
Content-Length: 47
Connection: keep-alive
Last-Modified: Sun, 27 Jan 2019 21:56:05 GMT
Cache-Control: max-age=15552000
Access-Control-Allow-Origin: *
X-Varnish: 402685964
Age: 0
Via: 1.1 varnish-v4
``` 

are you still experiencing the same error?

The second error you have reported (in Melown Cloud) is know minor bug in our frontend and will be fixed in the next release. Nevertheless it shouldn't prevent your resource from displaying in your maps. I have checked your map [1] with this resource and it works fine. 

Regards,
Tomas

[1] : https://www.melown.com/cloud/link/rDwaBnOq7XDCm8Wveojd

**Comment by jrjdavidson** [comment]
Hi Tomas,
It all seems to be working fine now! 
Thanks,
JD
