### ISSUE TITLE
Dbl click outside frame will move map.

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-browser-js#145]
HI, when embedding a vts-browser in a webpage, a double-click outside the frame will cause the map to move, see screenshot.
![audiodisplay 1](https://user-images.githubusercontent.com/46798391/53525850-9761da00-3b47-11e9-8385-ebab7b35627c.gif)

**Comment by DavidLevinsky** [comment]
Hi, thanks for the feedback. I will try to fix it in next release.

**Comment by DavidLevinsky** [comment]
It should be fixed in current version 2.19.1.

**Comment by jrjdavidson** [comment]
Hi David, 
Thanks for getting on this so quick- seems something went wrong though, double-click doesn't work at all anymore on any maps that are launched by JS? You can see it here: https://www.holoceneadventures.com/RMC/

**Comment by DavidLevinsky** [comment]
Sorry. It should be fixed in current version 2.19.2.
