### ISSUE TITLE
Is it possible to use the "viewfinder-1-arc-sec" data from melown's CDN?

### ISSUE THREAD

**Issue by fnicollet** [Melown/vts-browser-js#72]
Hello,

In the examples, mapConfig files are loaded from melown's CDN:
https://cdn.melown.com/mario/store/melown2015/map-config/melown/VTS-Tutorial-map/mapConfig.json
with URLs relative to the CDN for glues and meta ("metaUrl" : "../../../stage/glues/melown-viewfinder-world_melown-viewfinder-1-arc-sec/{lod}-{x}-{y}.2dmeta?1", etc.).

I tried the "basic" demo from the repo, saved the mapConfig.json file next to my index and edited it. I tried changing the "../../../" paths to the CDN, but with no success. It seems like sometimes the base URL is "http://cdn.melown.com/mario/store/", sometimes it's "http://cdn.melown.com/mario/proxy/", depending on the resource.
It looks like the CORS headers are present, to allow for cross-domain access.
So a couple of questions:
- Is it allowed (legally speaking) to use the ressources (glues and stuff) from melown's CDN or is it forbidden? The project is open-source but generating/hosting all those files must be costy, so it would make sense
- If it is not allowed, is there a way to download the DEM and generate the glues on my own VTS-backend? Is there a documented procedure?
- If it is allowed, how do you create a mapConfig.json file for remote access to the CDN ressources

Thanks a lot,
Fabien

**Comment by DavidLevinsky** [comment]
Hello,

relative URLs are relative to the URL of the file in which are relative URLs present. Relative URLs in the mapConfig are relative to the mapConfig URL. Some parts of the mapConfig can be stored in the separate JSON files (e.g. bound layers, ...) In these cases relative URLs are relative to the JSON URL. 

The resources from the Melown's CDN are part of the [Melown Cloud Service](https://www.melown.com/products/cloud/#content) This service allows you to configure your own map from the set of the provided resources. Traffic is charged according to the pricing list. Small traffic is for free. The resources from the Melown's CDN will be protected by access key. At the present is protection disabled. Whether will be allowed to mix your VTS-Backend with Melown Cloud backed and under which conditions is not determined yet.  You should probably ask these questions to tomas.kavan@melown.com  Global DEM like Viewfinder can be downloaded from DEM related internet sites.

David

**Comment by fnicollet** [comment]
Thanks!
I emailed Thomas, and will look into viewfinder

Fabien

**Comment by tomasKavan** [comment]
Hello Fabien,

David already responded your questions pretty precisely. Melown Cloud resources must be used only in map configurations created by [Melown Cloud Console](https://www.melown.com/cloud) and due to licensing reasons it's not allowed to use them outside of cloud. 

Nevertheless some of resources in Melown Cloud have open or public license. Such datasets you can download from public sources and use them in your map proxy instance freely.

Tomas

**Comment by fnicollet** [comment]
Thanks!
I'll try to mass download the viewfinder files from the original source and make it available on my mapproxy instance.
If I get time, i'll try to document the process, could be a nice addition ot your documentation

Fabien
