### ISSUE TITLE
Minimum requirements melown

### ISSUE THREAD

**Issue by k-rns** [Melown/vts-browser-js#83]
Hi,

What are the minimum requirements to open the mars-case-study in a chrome browser? This is the link I'm trying to open, but it takes too long to respond. It sure works, since it can be openend on another computer. 
http://jetstream.signell.us:8070/mapproxy/mars-qsc/surface/mars-case-study/mars-mola-dem/?pos=obj,-77.442856,-7.249034,fix,3502.77,-78.57,-30.97,0.00,261871.59,45.00

I have a windows 10 Home device with these properties: 
![knipsel](https://user-images.githubusercontent.com/7288408/30762726-6f5e5a8e-9fe3-11e7-8393-554e7c604002.PNG)

Is it the computer properties that do not comply or are there any chrome settings or AdBlock settings that need to be adjusted?

Thanks a lot
Karen

**Comment by rsignell-usgs** [comment]
@jachym or @tomasKavan , the machine that @k-rns has would seem sufficient to render the Mars demo, no?    It would be nice if we could figure this out, since we were hoping @k-rns could work for us remotely on setting up some of our data with Melown.

**Comment by DavidLevinsky** [comment]
Hello Karen, your computer HW is more than enough for running VTS Browser. Does any other VTS Browser demo works for you? For example:

**Comment by DavidLevinsky** [comment]
Hello Karen, your computer HW is more than enough for running VTS Browser. Does any other VTS Browser demo works on your comupter? For example:
https://www.melown.com/intergeo2016/
Is your computer WebGL capable? Please try this test:
http://webglreport.com/
It is possible that it is cased by your antivirus / firewall or some other security protection mechanism. You demo is hosted on the port :8070 which some application may consider as unreliable. The link that you provided me works on my computer very well. It even works on my cell phone (LG G6). Please try to open your link in chrome browser and open Developer tools panel ( Ctrl+Shift+I ) and select console and then reload the page. In case you find some errors logged in the console, send me these logs and I will try to investigate it further.

**Comment by k-rns** [comment]
Hi @DavidLevinsky , sorry for the late response. Indeed I think you're right, it's probably the firewall or security mechanism from the network I've been working on. I can open it fine opening the application from another place and it works just fine. Very happy it is not the computer requirements being the problem. Thanks!
