### ISSUE TITLE
distance between coords

### ISSUE THREAD

**Issue by tomasjohn** [Melown/vts-browser-js#86]
Hi! **getDistance** works just fine with wgs84 _Coords_

Is there a way how to use API to measure a distance between the camera position and _navCoords_, including heights?

**Comment by DavidLevinsky** [comment]
Probably most simple way how to do it  is by using following method:

**Comment by DavidLevinsky** [comment]
Probably most simple way how to do it, is by using following method:

convertCoordsFromNavToCameraSpace(coords, heightMode)

more information about this method can be found in the [documentation](https://github.com/Melown/vts-browser-js/wiki/VTS-Browser-Map-API#methods-for-conversions)

Camera space coordinates are Cartesian and relative to the camera (camera position is [0,0,0]). So distance can be computed following way:

distance = sqrt(x^2 + y^2 + z^2) where x,y,z are camera space coordinates
