### ISSUE TITLE
2D points visibility problem

### ISSUE THREAD

**Issue by tomasjohn** [Melown/vts-browser-js#87]
Hi! After rewriting to the **vts**.browser I'm struggeling with 2D points, they are not beeing hidden. 

Can I check point's visibility? It was able to set a parameter to switch off the check of a visibility before, but I am unable to find it now.

Attaching a video preview of the problem.
[2D Points Melown VTS - Google Chrome 31.10.2017 17_08_23.zip](https://github.com/Melown/vts-browser-js/files/1454181/2D.Points.Melown.VTS.-.Google.Chrome.31.10.2017.17_08_23.zip)

**Comment by DavidLevinsky** [comment]
I do not know which method was used for rendering points. In case that it was:

renderer.drawImage(params);

You have to set set following parameters to enable visibility test:

            depthTest : true,
            depthOffset : [-0.01,0,0]

more details depthOffset paramater can be found in [documentation](https://github.com/Melown/vts-browser-js/wiki/VTS-Browser-Renderer-API#definition-of-depthoffset). 

I have modified demo [example](https://jsfiddle.net/anxgpn3y/) to demonstrate these chages.

In case you are rendering vector features which are static (no animations needed) then you should consider geodata for rendering these features.

You can find geodata examples [here](https://github.com/Melown/vts-browser-js/wiki/Examples) and documentation can be found [here](https://github.com/Melown/vts-browser-js/wiki/VTS-Browser-Map-API#geodata-creation).
