### ISSUE TITLE
Why is Melown making so many requests on a low altitude map?

### ISSUE THREAD

**Issue by fnicollet** [Melown/vts-browser-js#92]
Hello,

I am coming back to Melown and comparing it to other 3D viewers and something that I noted is that melown makes about 1000 requests by default for the "Hello World" example:
https://jsfiddle.net/a5rh6vnh/2/
Looking at the Network panel, it looks like Melown loads ALL the tile pyramid from Z0 to initial zoom. So it requesting all the antarctica tiles (imagery and terrain) for some reasons that I can't understand
I noticed that Cesium and iTowns have the same behaviour, so there must be a technical reason behind this I guess ....

Can you give me an explanation as to why it doesn't just load the necessary levels?

Thanks,
Fabien

**Comment by DavidLevinsky** [comment]
Hello Fabien,

you are right. In the default load mode vts-browser loads  all the tile pyramid from Z0 to initial zoom. Reason why industry uses this approach is that this way you always have something loaded no mater where you move, jump, fly, ... from initial position, so something is always visible and you don't loose context. Drawback of this solution is that you load more tiles that is needed for displaying specific position in the map. 

Good news is that vts-browser also supports different load mode.  All you need to do is set following browser option:

`mapLoadMode: "fit"`

This mode loads only tiles which are needed. In places where tiles are not yet loaded is displayed grid. You ca try it in following example:

https://jsfiddle.net/ufzpe6jm/

**Comment by fnicollet** [comment]
Thanks a lot for your answer, that's exactly the setting I needed, the map loads really fast that way and zooming out/panning still loads the necessary tiles on demand, amazing :)
